- name: Create certificate directory
  ansible.builtin.file:
    path: ~/ssl/crt/
    state: directory
    mode: a+rw
    
- name: Create signing request directory
  ansible.builtin.file:
    path: ~/ssl/csr
    state: directory
    mode: a+rw
- community.crypto.openssl_privatekey:
    path: "{{ key_path }}"
    size: 4096

- community.crypto.openssl_csr:
    path: "{{ csr_path }}"
    privatekey_path: "{{ key_path }}"

- community.crypto.x509_certificate:
    provider: selfsigned
    path: "{{ crt_path }}"
    privatekey_path: "{{ key_path }}"
    csr_path: "{{ csr_path }}"
